repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v2.5.0"
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args: ["--ignore=E203,W503,E501"]

-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
        entry: black
        language: system
        types: [ python ]
        args: [ --line-length=120 ]
